// Generated by CoffeeScript 1.10.0
(function() {
  var YAML, arg, args, async, data, join, key, messages, pargs, path, ref, resolve, yaml;

  ref = require("path"), resolve = ref.resolve, join = ref.join;

  async = require("fairmont").async;

  YAML = require("js-yaml");

  messages = require("./index");

  args = process.argv.slice(2);

  pargs = [];

  while (args.length > 0) {
    arg = args.shift();
    switch (arg) {
      case "--data":
        yaml = args.shift();
        break;
      default:
        pargs.push(arg);
    }
  }

  path = pargs[0], key = pargs[1];

  data = {};

  async(function*() {
    var error, error1, error2, error3, internal, message;
    internal = (yield messages(join(__dirname, "..", "messages.yaml")));
    if (!((path != null) && (key != null))) {
      internal.abort("help.usage");
    }
    try {
      message = (yield messages(resolve(path))).message;
    } catch (error1) {
      error = error1;
      internal.abort("errors.bad-path", {
        path: path
      });
    }
    if (yaml != null) {
      try {
        data = YAML.safeLoad(yaml);
      } catch (error2) {
        internal.abort("errors.bad-yaml", {
          yaml: yaml
        });
      }
    }
    try {
      return console.log(message(key, data));
    } catch (error3) {
      return internal.abort("errors.bad-key");
    }
  })();

}).call(this);
